### ISSUE TITLE
junit.framework.AssertionFailedError: App crashes on webview creations for certain devices

### ISSUE THREAD

**Issue by markharding** [Minds/mobile#13]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.minds.mobile/com.minds.mobile.MainActivity}: java.lang.RuntimeException: Failed to create webview. 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2316)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376)
at android.app.ActivityThread.access$800(ActivityThread.java:147)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5253)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.RuntimeException: Failed to create webview. 
at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:82)
at org.apache.cordova.CordovaActivity.makeWebViewEngine(CordovaActivity.java:191)
at org.apache.cordova.CordovaActivity.makeWebView(CordovaActivity.java:187)
at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:135)
at org.apache.cordova.CordovaActivity.loadUrl(CordovaActivity.java:209)
at com.minds.mobile.MainActivity.onCreate(MainActivity.java:32)
at android.app.Activity.performCreate(Activity.java:5975)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
... 10 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
at org.apache.cordova.CordovaWebViewImpl.createEngine(CordovaWebViewImpl.java:80)
... 18 more
Caused by: junit.framework.AssertionFailedError: Please extend XWalkActivity for shared mode
at junit.framework.Assert.fail(Assert.java:50)
at org.xwalk.core.XWalkCoreWrapper.initEmbeddedMode(XWalkCoreWrapper.java:111)
at org.xwalk.core.XWalkPreferences.setValue(XWalkPreferences.java:105)
at org.crosswalk.engine.XWalkCordovaView.setGlobalPrefs(XWalkCordovaView.java:40)
at org.crosswalk.engine.XWalkCordovaView.<init>(XWalkCordovaView.java:51)
at org.crosswalk.engine.XWalkWebViewEngine.<init>(XWalkWebViewEngine.java:56)
... 21 more
```

Reported platforms:
```
Android 5.0
Android 4.4
```

Possibly x86 architecture.

**Comment by markharding** [comment]
Crosswalk bug: https://crosswalk-project.org/jira/browse/XWALK-3961

**Comment by markharding** [comment]
Closed. Uploads x86 build to google play also.
