### ISSUE TITLE
java.lang.NullPointerException: Cyanogenmod camera access crash

### ISSUE THREAD

**Issue by markharding** [Minds/mobile#14]
On avatar selection reports crash report:

```
java.lang.RuntimeException: Unable to resume activity {com.minds.mobile/com.minds.mobile.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=18, result=-1, data=Intent { dat=content: flg=0x1 }} to activity {com.minds.mobile/com.minds.mobile.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.success(java.lang.String)' on a null object reference
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3224)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3257)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
at android.app.ActivityThread.access$800(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5696)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=18, result=-1, data=Intent { dat=content: flg=0x1 }} to activity {com.minds.mobile/com.minds.mobile.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.success(java.lang.String)' on a null object reference
at android.app.ActivityThread.deliverResults(ActivityThread.java:3881)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3197)
... 11 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CallbackContext.success(java.lang.String)' on a null object reference
at org.apache.cordova.camera.CameraLauncher.processResultFromGallery(CameraLauncher.java:613)
at org.apache.cordova.camera.CameraLauncher.onActivityResult(CameraLauncher.java:695)
at org.apache.cordova.CordovaInterfaceImpl.onActivityResult(CordovaInterfaceImpl.java:120)
at org.apache.cordova.CordovaActivity.onActivityResult(CordovaActivity.java:321)
at android.app.Activity.dispatchActivityResult(Activity.java:6160)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3877)
... 12 more
```

**Comment by markharding** [comment]
Bug report sent to https://issues.apache.org/jira/browse/CB-9189
